from stringConverter import *

# test for the stringConVerter class, run this script and the last line should say "all success = True"

print("0 should be V0000")
print("intToVString(0) = " + intToVString(0))
test0 = "V0000" == intToVString(0)
print("Success = " + str(test0))
print("------------------------")

print("1 should be V0001")
print("intToVString(1) = " + intToVString(1))
test1 = "V0001" == intToVString(1)
print("Success = " + str(test1))
print("------------------------")
print("10 should be V0010")
print("intToVString(10) = " + intToVString(10))
test2 = "V0010" == intToVString(10)
print("Success = " + str(test2))
print("------------------------")
print("100 should be V0100")
print("intToVString(100) = " + intToVString(100))
test3 = "V0100" == intToVString(100)
print("Success = " + str(test3))
print("------------------------")

print("-1 should be V-001")
print("intToVString(-1) = " + intToVString(-1))
test4 = "V-001" == intToVString(-1)
print("Success = " + str(test4))
print("------------------------")
print("-10 should be V-010")
print("intToVString(-10) = " + intToVString(-10))
test5 = "V-010" == intToVString(-10)
print("Success = " + str(test5))
print("------------------------")
print("-100 should be V-100")
print("intToVString(-100) = " + intToVString(-100))
test6 = "V-100" == intToVString(-100)
print("Success = " + str(test6))
print("------------------------")

print("0 should be V0000")
print("intToHString(0) = " + intToVString(0))
test7 = "V0000" == intToVString(0)
print("Success = " + str(test0))
print("------------------------")

print()
print()

print("1 should be H0001")
print("intToHString(1) = " + intToHString(1))
test8 = "H0001" == intToHString(1)
print("Success = " + str(test8))
print("------------------------")
print("10 should be H0010")
print("intToHString(10) = " + intToHString(10))
test9 = "H0010" == intToHString(10)
print("Success = " + str(test9))
print("------------------------")
print("100 should be H0100")
print("intToHString(100) = " + intToHString(100))
test10 = "H0100" == intToHString(100)
print("Success = " + str(test10))
print("------------------------")

print("-1 should be H-001")
print("intToHString(-1) = " + intToHString(-1))
test11 = "H-001" == intToHString(-1)
print("Success = " + str(test11))
print("------------------------")
print("-10 should be H-010")
print("intToHString(-10) = " + intToHString(-10))
test12 = "H-010" == intToHString(-10)
print("Success = " + str(test12))
print("------------------------")
print("-100 should be H-100")
print("intToHString(-100) = " + intToHString(-100))
test13 = "H-100" == intToHString(-100)
print("Success = " + str(test13))
print("------------------------")



print("all success = " + str(test0 & test1 & test2 & test3 & test4 & test5 & test6 & test7 & test8 & test9 & test10 & test11 & test12 & test13))

# print(test0)
# print(test1)
# print(test2)
# print(test3)
# print(test4)
# print(test5)
# print(test6)
# print(test7)
# print(test8)
# print(test9)
# print(test10)
# print(test11)
# print(test12)
# print(test13)